<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Previous</name>
   <tag></tag>
   <elementGuidId>94608b4b-6e71-472e-8420-d043e16eb0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselExampleIndicators']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.carousel-control-prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>60715239-6936-4be5-b482-4dc4349604de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-prev</value>
      <webElementGuid>e64bfd39-33de-47a0-9fba-218ef337da8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#carouselExampleIndicators</value>
      <webElementGuid>6805f0b1-fabe-4672-859e-135337cab14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b59eaac-b7d5-4532-a94c-d92409723cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slide</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>64f00109-40ef-490f-bb4a-bb6f68a69af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          Previous
        </value>
      <webElementGuid>270eb602-12c5-4be1-8d8b-2a3a107f119f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselExampleIndicators&quot;)/a[@class=&quot;carousel-control-prev&quot;]</value>
      <webElementGuid>ca0f36ec-d248-4497-8475-259cfe4e7d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselExampleIndicators']/a</value>
      <webElementGuid>3a223139-ffb2-440d-a72c-9c434dcf83eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[5]</value>
      <webElementGuid>04a41b74-49c3-4950-b158-7139567cf57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/following::a[8]</value>
      <webElementGuid>33c67c7e-ec49-4888-a864-9a28bd3b8aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[1]</value>
      <webElementGuid>ecfa250d-cf96-4f18-8828-f9dc2a6c32a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#carouselExampleIndicators')]</value>
      <webElementGuid>777eaa5a-69a9-4757-9237-5bbf468b60a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>19123558-f95d-41ed-a435-2a35ebb2f90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#carouselExampleIndicators' and (text() = '
          
          Previous
        ' or . = '
          
          Previous
        ')]</value>
      <webElementGuid>10054580-24a0-4847-b557-fa99d8e881b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
